# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'server.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(394, 320)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #121212;\n"
"    color: #ffffff;\n"
"    font-family: Segoe UI, Roboto, Arial;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* Campos de texto */\n"
"QLineEdit, QSpinBox {\n"
"    background-color: #1e1e1e;\n"
"    color: white;\n"
"    border: 1px solid #3c3c3c;\n"
"    border-radius: 5px;\n"
"    padding: 6px;\n"
"    selection-background-color: #555;\n"
"    selection-color: white;\n"
"}\n"
"\n"
"/* Labels */\n"
"QLabel {\n"
"    color: #e0e0e0;\n"
"}\n"
"\n"
"/* Botões */\n"
"QPushButton {\n"
"    background-color: #2c2c2c;\n"
"    color: white;\n"
"    border: 1px solid #4c4c4c;\n"
"    border-radius: 6px;\n"
"    padding: 8px 16px;\n"
"    font-weight: bold;\n"
"    transition: background-color 0.3s;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3a3a3a;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1a1a1a;\n"
"}\n"
"\n"
"/* Remove foco azul padrão */\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 30))
        self.pushButton.setMaximumSize(QtCore.QSize(71, 23))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setMinimumSize(QtCore.QSize(113, 30))
        self.lineEdit.setMaximumSize(QtCore.QSize(113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(376, 143))
        self.frame_2.setMaximumSize(QtCore.QSize(376, 143))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(90, 0, 100, 40))
        self.label.setMinimumSize(QtCore.QSize(100, 40))
        self.label.setMaximumSize(QtCore.QSize(100, 40))
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 100, 150, 40))
        self.pushButton_2.setMinimumSize(QtCore.QSize(150, 40))
        self.pushButton_2.setMaximumSize(QtCore.QSize(101, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.spinBox = QtWidgets.QSpinBox(self.frame_2)
        self.spinBox.setGeometry(QtCore.QRect(90, 40, 200, 30))
        self.spinBox.setMinimumSize(QtCore.QSize(200, 30))
        self.spinBox.setMaximumSize(QtCore.QSize(161, 22))
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.frame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Open DB"))
        self.lineEdit.setText(_translate("MainWindow", "Port"))
        self.label.setText(_translate("MainWindow", "Threds"))
        self.pushButton_2.setText(_translate("MainWindow", "Start"))